import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
const inter = Inter({ subsets: ["latin"] });
import { CartProvider } from "@/utils/ContextReducer";
export const metadata = {
  title: "Mini Restaurant - App ",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <ThemeProvider attribute="class">
            <div className="min-h-screen w-full flex flex-col justify-between">
              <div>
                <Navbar />

                {children}

              </div>
              <Footer />
            </div>
          </ThemeProvider>
        </CartProvider>
      </body>
    </html>
  );
}
